### ISSUE TITLE
[1.14.4] Exception on server startup when using SQLite database

### ISSUE THREAD

**Issue by PotatoSauceVFX** [PotatoSauceVFX/Whitelist-Sync-2#9]
The exception doesn't crash the server or change anything from what I've seen.
`[Finalizer/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.NullPointerException: null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:20) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClass(ModLauncherService.java:19) [eventbus-1.0.0-service.jar:1.0.0+54+3f83a9e]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102) [modlauncher-4.1.0.jar:4.1.0+62+5bfa59b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-4.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_191]
	at org.sqlite.core.DB.newSQLException(DB.java:907) [?:?]
	at org.sqlite.core.CoreStatement.internalClose(CoreStatement.java:115) [?:?]
	at org.sqlite.jdbc3.JDBC3Statement.close(JDBC3Statement.java:35) [?:?]
	at org.sqlite.jdbc4.JDBC4Statement.close(JDBC4Statement.java:27) [?:?]
	at org.sqlite.jdbc3.JDBC3Statement.finalize(JDBC3Statement.java:42) [?:?]
	at java.lang.System$2.invokeFinalize(Unknown Source) [?:1.8.0_191]
	at java.lang.ref.Finalizer.runFinalizer(Unknown Source) [?:1.8.0_191]
	at java.lang.ref.Finalizer.access$100(Unknown Source) [?:1.8.0_191]
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source) [?:1.8.0_191]
`

**Comment by PotatoSauceVFX** [comment]
9ec5004f693ff6acfdd6c35632c452c6b31820c8 should have fixed this issue.
